import type { MetadataRoute } from "next";

/**
 * Web app manifest (served at /manifest.webmanifest — Next auto-links it).
 *
 * Colors sampled from globals.css: --color-ink/--color-oxford #0b0829
 * (near-black, used for the standalone title bar), --color-canvas #ffffff
 * (the app's light-theme boot surface, so the splash matches first paint).
 * Icons are generated by scripts/generate-pwa-icons.mjs — the brand's
 * orange "A" (#ff8400) on the near-black field.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "RAI — Solar Diligence Copilot",
    short_name: "RAI",
    description:
      "AI due-diligence copilot for solar capital projects racing the ITC deadline.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    theme_color: "#0b0829",
    background_color: "#ffffff",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
